name: pages
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:3.21
    steps:
      - name: deps  # submodules needs git, upload-pages-artifact needs gnu tar
        run: apk add npm ruby-bundler jekyll ruby-rake ruby-dev make gcc musl-dev g++ git tar
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: npm deps
        run: npm ci
      - name: ruby deps
        run: bundle install -j $(nproc)
      - name: npm copy
        run: npm run copy-vendor
      - name: rougify
        run: |
          bundle exec rougify style base16.solarized.dark | sed 's/002b36/202124/g' >> _sass/minimal-mistakes/skins/_custom.scss
          bundle exec rougify style base16.solarized.light >> _sass/minimal-mistakes/skins/_custom-light.scss
      - name: jekyll
        run: bundle exec jekyll build
      - uses: actions/upload-pages-artifact@v4
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
